### PR TITLE
Updated DT Series data from GoodWe documentation (shared to Discord channel)

### PR DESCRIPTION
**Pull request by nicve**

### CODE REVIEW

**Comment by madtempest** [comment]
I have run this PR and can confirm that on my SDT G2 unit I am getting some of the new values.

```
Identified inverter
- Model:
- SerialNr: 5
- Rated power: 0
- A/C output type: None
- Firmware: 20.20.38
- ARM firmware: None
- Modbus version: None
- DSP1 version: 20
- DSP2 version: 20
- DSP svn version: 1243
- Arm version: 56
- ARM svn version: 124

2024-08-11 15:01:04,183 read_runtime_data(233) - INFO: Meter values not supported, disabling further attempts.
timestamp:               Timestamp = 2024-05-11 20:51:00
vpv1:            PV1 Voltage = 494.5 V
ipv1:            PV1 Current = 2.9 A
ppv1:            PV1 Power = 1434 W
vpv2:            PV2 Voltage = 481.6 V
ipv2:            PV2 Current = 9.4 A
ppv2:            PV2 Power = 4527 W
ppv:             PV Power = 5961 W
vline1:                  On-grid L1-L2 Voltage = 426.2 V
vline2:                  On-grid L2-L3 Voltage = 427.0 V
vline3:                  On-grid L3-L1 Voltage = 427.5 V
vgrid1:                  On-grid L1 Voltage = 244.1 V
vgrid2:                  On-grid L2 Voltage = 244.3 V
vgrid3:                  On-grid L3 Voltage = 251.1 V
igrid1:                  On-grid L1 Current = 7.9 A
igrid2:                  On-grid L2 Current = 8.0 A
igrid3:                  On-grid L3 Current = 7.9 A
fgrid1:                  On-grid L1 Frequency = 50.02 Hz
fgrid2:                  On-grid L2 Frequency = 50.02 Hz
fgrid3:                  On-grid L3 Frequency = 50.02 Hz
pgrid1:                  On-grid L1 Power = 1928 W
pgrid2:                  On-grid L2 Power = 1954 W
pgrid3:                  On-grid L3 Power = 1984 W
total_inverter_power:            Total Power = 5864 W
work_mode:               Work Mode code = 1
work_mode_label:                 Work Mode = Normal
error_codes:             Error Codes = 0
warning_code:            Warning code = 0
apparent_power:                  Apparent Power = 0 VA
reactive_power:                  Reactive Power = -122 var
total_input_power:               Total Input Power = 0 W
power_factor:            Power Factor = 0.999
temperature:             Inverter Temperature = 37.0 C
temperature_heatsink:            Heatsink Temperature = None C
e_day:           Today's PV Generation = 21.5 kWh
e_total:                 Total PV Generation = 839.3 kWh
h_total:                 Hours Total = 345 h
safety_country:                  Safety Country code = 32
safety_country_label:            Safety Country = 50Hz 230Vac Default
functionbit:             FunctionBit = 266
vbus:            Bus Voltage = 641.3 V
vnbus:           NBus Voltage = 323.5 V
derating_mode:           Derating Mode code = 32
derating_mode_label:             Derating Mode = Export power derating
rssi:            RSSI = 101
```

Interestingly,  I can see in the commit that there is some changes here:

```
    __all_settings: tuple[Sensor, ...] = (
        Timestamp("time", 40313, "Inverter time"),

        Integer("shadow_scan", 40326, "Shadow Scan", "", Kind.PV),
        Integer("shadow_scan_pv1", 40326, "Shadow Scan Status PV1", "", Kind.PV),
        Integer("shadow_scan_pv2", 40352, "Shadow Scan Status PV2", "", Kind.PV),
        Integer("shadow_scan_pv3", 40362, "Shadow Scan Status PV3", "", Kind.PV),
        Integer("shadow_scan_pv1_time", 40347, "Shadow Scan PV1 Time", "", Kind.PV),
        Integer("shadow_scan_pv2_time", 40353, "Shadow Scan PV2 Time", "", Kind.PV),
        # Integer("shadow_scan_pv3_time", 40xxx, "Shadow Scan PV3 Time", "", Kind.PV),  #TBC
        Integer("grid_export", 40327, "Grid Export Limit Enabled", "", Kind.GRID),
        Integer("grid_export_limit", 40328, "Grid Export Limit", "%", Kind.GRID),
        Integer("start", 40330, "Start / Power On", "", Kind.GRID),
```
        
and what caught my eye specifically is  ` Integer("grid_export_limit", 40328, "Grid Export Limit", "%", Kind.GRID),` as I do not get this value in my output above however `print(asyncio.run(inverter.get_grid_export_limit()))` does give me the value I am expecting.

**Comment by mletenay** [comment]
Sorry for some delay, I had less time over past few weeks.
They seem to be fine, but I want to checkout and test them a bit before approving.

**Comment by nicve** [comment]
Thanks. Did you see the documentation provided on Discord? I was sent a full excel spreadsheet of DT Series registers by GoodWe support. I am sure you could get even more out of it than my crude attempt here.

**Comment by mletenay** [comment]
Thanks and sorry for the delay ...

**Pull request merged**
